export const APP_ROUTES = {
  Dashboard: "/dashboard",
  Admin: "/admin",
  Schedule: "/schedule",
  BarberSchedule: "/barber/schedule",
  Payments: "/payments",
  Services: "/services",
  Barbers: "/barbers",
  Customers: "/customers",
  Login: "/login",
  Register: "/register",
  WorkingHours: "/settings/working-hours",
  TimeOff: "/settings/time-off",
  BookingRules: "/settings/booking-rules",
} as const;
